### PR TITLE
An Arabic translation of the template's strings

### PR DESCRIPTION
**Pull request by agharbeia**

### CODE REVIEW

**Comment by mahmoud** [comment]
Looks pretty good on first glances. I think I have a friend who can review, and if all looks good, I'll merge and we'll get this set up ASAP.

**Comment by agharbeia** [comment]
Any news? We'd like to promote it as part of our organisation's continuous support to Wikipedia in general and the Arabic wikipedia community specifically.

**Comment by mahmoud** [comment]
Yep! I just heard back from my friend who says it's all good! Thanks for your patience (and the translation!) Stephen's getting this set up ASAP.

**Comment by slaporte** [comment]
Thank you! 

@agharbeia How does this look? http://top.hatnote.com/ar/

Any interest in a newsletter of the most edited articles on Arabic Wikipedia too?

 - http://weekly.hatnote.com/
 - https://github.com/hatnote/weeklypedia
 - https://github.com/hatnote/weeklypedia/blob/master/weeklypedia/issue_templates/strings/en_strings.yaml

**Comment by agharbeia** [comment]
The main title sounds awkward. I guess it's because it's comprised of two independent strings put together: `language_project` and `title`

It doesn't sound natural. I couldn't anticipate that from the source strings
I should have looked at the templates' themselves.

Is there a possibility to fix the ordering of strings in the Arabic template and add a conjunction between the two strings?
I can do it, if it is technically possible.

There's also a minor fix in the gender of a pronoun in the about section.

**Comment by slaporte** [comment]
If there are slight tweaks you can't do in the strings file, you can edit the template directly and send a pull request: https://github.com/hatnote/top/blob/master/top/templates/ar_chart.dust

Thanks again for your help!

**Pull request merged**
